-- Star Schema: Pattern Group >> Patterns and their recipient groups from ZPA >> WILL HAVE TO BE MAINTAINED!!!!
SELECT 
	pg.PATTERN_CODE
	,pg.OWNER_GROUP
	,CASE
		WHEN pg.ZPA_STATUS = 1 THEN 'Active'
		ELSE 'Inactive'
	END AS ZPA_STATUS
	,pg.PATTERN_SCHEDULE
	,pg.PATTERN_SCHEDULE_RUN_DAY
	,pg.LAST_UPDATED_DTTM
FROM i2_data.dbo.PROFITECT_PATTERNS_BY_OWNER_GROUP pg
ORDER BY
	1 DESC
	;

-- Star Schema: NAVEX COMMENTS 
SELECT 
	n.CASE_NUMBER
	,n.DETAILS AS COMMENTS
	,n.OPENED
	,n.LAST_MODIFIED
FROM i2_data.dbo.NAVEX_ETHICSPOINT_CASE_DATA n
WHERE
	n.OPENED BETWEEN '2023-07-01 00:00:00.001' AND GETDATE()
--	((CONVERT(int,GETDATE()-1) - CONVERT(int,n.OPENED)) / 90) < 1 -- Rolling 90 days >> Changed 8.2.2023 to starting July 2023
	AND n.BRANCH_NUMBER LIKE '%Store%'
	AND n.BRANCH_NUMBER IS NOT NULL
ORDER BY
	3 DESC, 4
	;

-- APM Store List (aka NODE_ADDRESS)
	-- Only active APMs / terminated APMs filtered out
	-- PBIX Relationships updated
		-- [APMs] >> [All Patterns] 
			-- Cross-Filter Direction = Single ('APMs' filters 'All Patterns')
		-- [APMs] >> [NAVEX] 
			-- Cross-Filter Direction = Single ('APMs' filters 'NAVEX')
SELECT
	apm.POC_APM_EMP_NUM AS APM_Emp_Num
	,apm.NODE_ADDRESS
	,emp.FIRST_NAME
	,emp.LAST_NAME
	,emp.FIRST_NAME + ' ' + emp.LAST_NAME AS APM_FULL_NAME
--	,emp.WORK_EMAIL_ADDRESS
--	,emp.JOB_TITLE
FROM i2_Data.dbo.ATLAS_CONTACTS apm
LEFT OUTER JOIN i2_data.dbo.EISB_LP_FEED emp
	ON apm.POC_APM_EMP_NUM = emp.EMP_NUMBER
WHERE
	apm.POC_APM_EMP_NUM IS NOT NULL
	;

-- List of all stores + location data
	-- Updated to join active APMs to have complete list of their active stores
		-- Goal is to have 0 null locations
		-- APMs not listed on query
SELECT 
	r.LOC_NUM AS REGION_NUMBER
	,CONCAT(r.[NAME], ' (', r.LOC_NUM, ')' ) AS REGION
	,a.LOC_NUM AS AREA_NUMBER
	,CONCAT(a.[NAME], ' (', a.LOC_NUM, ')' ) AS AREA
	,d.LOC_NUM AS DISTRICT_NUMBER
	,CONCAT(d.[NAME], ' (', d.LOC_NUM, ')' ) AS DISTRICT
	,s.LOC_NUM AS STORE_NUMBER
	,CONCAT(FORMAT(s.LOC_NUM,'00000'),' - ',s.CITY,', ',s.ADDRESS_LINE_1,', ',s.[STATE]) AS Store
FROM i2_Data.dbo.LOCATION s
LEFT OUTER JOIN i2_Data.dbo.ATLAS_CONTACTS apm
	ON apm.NODE_ADDRESS = s.NODE_ADDRESS
LEFT OUTER JOIN i2_Data.dbo.LOCATION d
	ON s.PARENT_LOCATION_NUMBER = d.LOC_NUM AND s.PARENT_LOCATION_TYPE_CODE = d.LOC_TYPE_CODE
LEFT OUTER JOIN i2_Data.dbo.LOCATION a
	ON d.PARENT_LOCATION_NUMBER = a.LOC_NUM AND d.PARENT_LOCATION_TYPE_CODE = a.LOC_TYPE_CODE
LEFT OUTER JOIN i2_Data.dbo.LOCATION r
	ON a.PARENT_LOCATION_NUMBER = r.LOC_NUM AND a.PARENT_LOCATION_TYPE_CODE = r.LOC_TYPE_CODE
WHERE
	s.LOC_TYPE_CODE = 'S'
	AND apm.POC_APM_EMP_NUM IS NOT NULL
--	AND s.OPEN_DATE IS NOT NULL
--	AND s.CLOSE_DATE IS NULL
	;

-- with join of APM Contact + EMP Table
	-- Query v2: removed LOCATION table
		-- LOCATION table removed bc it is not needed and returned same output 
	-- Query v3: Added Primary Issue + Subcategories 1 & 2
	-- Query v4: Updated CASE statement to fix n.BRANCH_NUMBER
	-- Query v5: Removed emp table
SELECT 
	n.CASE_NUMBER
	,n.[STATUS]
	,n.CASE_TYPE
	,n.PRIMARY_ISSUE
	,n.PRIMARY_ISSUE_SUBCATEGORY_1
	,n.PRIMARY_ISSUE_SUBCATEGORY_2
	,n.ASSIGNEE AS APD
	,apm.POC_APM_EMP_NUM AS APM_Emp_Num
	,n.BRANCH_NUMBER
	,CAST(
		REPLACE(
			REPLACE(
				REPLACE(n.BRANCH_NUMBER
					,'Store','')
				,' ','')
			,'-','')
		AS int) AS STORE_NUM
	,n.LOCATION_ADDRESS
	,n.LOCATION_CITY
	,n.LOCATION_STATE_PROVINCE
	,n.REGION
	,n.REGION_NUMBER
	,n.AREA_NAME
	,n.AREA_NUMBER
	,n.OPENED
	,MIN( n.LAST_MODIFIED ) MIN_LAST_MODIFIED
	,n.DATE_TIME_INSERTED
FROM i2_data.dbo.NAVEX_ETHICSPOINT_CASE_DATA n
LEFT OUTER JOIN i2_Data.dbo.ATLAS_CONTACTS apm
	ON CAST(RIGHT(apm.NODE_ADDRESS, 5) AS int) 
		= CAST(
			REPLACE(
				REPLACE(
					REPLACE(n.BRANCH_NUMBER
						,'Store','')
					,' ','')
				,'-','')
			AS int)
WHERE
	n.OPENED BETWEEN '2023-07-01 00:00:00.001' AND GETDATE()
--	((CONVERT(int,GETDATE()-1) - CONVERT(int,n.OPENED)) / 90) < 1 -- Rolling 90 days >> Changed 8.2.2023 to starting July 2023
	AND n.BRANCH_NUMBER LIKE '%Store%'
	AND n.BRANCH_NUMBER IS NOT NULL
GROUP BY
	n.CASE_NUMBER,n.[STATUS],n.CASE_TYPE,n.PRIMARY_ISSUE,n.PRIMARY_ISSUE_SUBCATEGORY_1,n.PRIMARY_ISSUE_SUBCATEGORY_2,n.ASSIGNEE
	,n.BRANCH_NUMBER,n.LOCATION_ADDRESS,n.LOCATION_CITY,n.LOCATION_STATE_PROVINCE,n.REGION
	,n.REGION_NUMBER,n.AREA_NAME,n.AREA_NUMBER,n.OPENED,n.DATE_TIME_INSERTED,apm.POC_APM_EMP_NUM
ORDER BY 
	n.CASE_NUMBER
	,CASE
		WHEN n.[STATUS] LIKE '%Unreviewed' THEN 1
		WHEN n.[STATUS] LIKE '%In Process' THEN 2
		WHEN n.[STATUS] LIKE '%Ready for Review' THEN 3
		WHEN n.[STATUS] LIKE '%Closed' THEN 4
			ELSE 9
		END
	,MIN_LAST_MODIFIED
	;



-- Below is P18.APM's version
-- Updated to reflect "lifetime" (July 2023 - Present) / Completed Alerts (WITHOUT useless)
	--  Previously truncated to have only ROLLING 90 DAYS
-- Updated to reflect EMP_NUMBER and removing names of ASSIGNEE/OWNERs from WHERE clause
SELECT 
	o.OPP_ID
	,o.SUMMARY
	,o.OPP_STATUS
	,o.OPP_RESOLUTION
	,o.OPP_VALUE
	,SUBSTRING(o.PATTERN_NAME, 1, PATINDEX('% %',REPLACE(o.PATTERN_NAME,'CP - ',''))+LEN('CP - ')) PATTERN_CODE
	,CASE
		WHEN o.ETHICSPOINT_CASE_NUMBER IN ('(none)',' ','1','0') THEN NULL 
		WHEN o.ETHICSPOINT_CASE_NUMBER LIKE '%.%' THEN NULL
		WHEN LEN( o.ETHICSPOINT_CASE_NUMBER ) < 6 THEN NULL
			ELSE o.ETHICSPOINT_CASE_NUMBER
		END AS ETHICSPOINT_CASE_NUMBER
		
	,o.ASSIGNEE
	,o.EMP_NUMBER_ASSIGNEE
	,CASE
		WHEN o.EMP_NUMBER_OWNER LIKE '%MGR%' THEN CAST(RIGHT(o.EMP_NUMBER_OWNER, 5) AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '2627994' AND o.[OWNER] = 'Rick Gaitan' THEN '1509257'
		WHEN o.EMP_NUMBER_OWNER = '1543428' AND o.[OWNER] = 'Store Manager 05463' THEN CAST('5463' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '1808676' AND o.[OWNER] = 'Store Manager 03197' THEN CAST('3197' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '1991504' AND o.[OWNER] = 'Store Manager 13705' THEN CAST('12705' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '1634916' AND o.[OWNER] = 'Store Manager 15010' THEN CAST('15010' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '2925478' AND o.[OWNER] = 'Store Manager 17217' THEN CAST('17217' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '2923967' AND o.[OWNER] = 'Store Manager 17684' THEN CAST('17684' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = 'SteeringCommittee' THEN CAST('SteeringCommittee' AS nvarchar)
			ELSE o.EMP_NUMBER_OWNER
		END AS EMP_NUMBER_OWNER 
	,CASE
			WHEN o.[OWNER] LIKE '%store manager%' THEN CAST( RIGHT(o.[OWNER], 5) AS int )
			WHEN LEFT(o.OPPORTUNITY_ENTITY, 7) LIKE '% -%' THEN CAST( LEFT(o.OPPORTUNITY_ENTITY, 5) AS int )
		END AS Store_Number
	,CASE
		WHEN 
			SUBSTRING(o.PATTERN_NAME, 1, 8) IN ( 'CP - 296','CP - 305','CP - 577' ) -- This is a list of patterns assigned to DM's OR Entity = District ***UPDATE AND CHECK IF ENTITY = DISTRICTS*** IF NO, DON'T USE. 
			AND	o.OPPORTUNITY_ENTITY LIKE '%(%' -- This was used to test the character count for Entity's = DISTRICTS >> 6 = Districts
			AND CHARINDEX(')',o.OPPORTUNITY_ENTITY) - CHARINDEX('(',o.OPPORTUNITY_ENTITY) = 6 -- This was used to test the character count for Entity's = DISTRICTS >> 6 = Districts
			THEN CAST( -- Find the DISTRICT NUMBER between ( ) 
					SUBSTRING(o.OPPORTUNITY_ENTITY, CHARINDEX('(',o.OPPORTUNITY_ENTITY) +1 
					,CHARINDEX(')',o.OPPORTUNITY_ENTITY) - CHARINDEX('(',o.OPPORTUNITY_ENTITY)-1) 
				AS int ) 
		END AS DISTRICT_NUMBER
	,o.OPPORTUNITY_ENTITY
	,o.[OWNER]
	,o.LABELS
	,o.OPP_GENERATED_TIME AS CreatedDate -- Added 9.23.2021 > Calendar Table Should be Modeled After This Date
	,MIN(o.LAST_MODIFIED) MIN_LAST_MODIFIED
	,o.DATE_INSERTED
FROM i2_data.dbo.PROFITECT_OPPORTUNITIES o
WHERE 
	o.OPP_STATUS NOT IN ('HISTORY','Deleted')
	AND o.SUMMARY NOT LIKE 'Welcome to%'
	AND o.OPP_GENERATED_TIME BETWEEN '2023-07-01 00:00:00.001' AND GETDATE()
	AND o.DATE_INSERTED BETWEEN '2023-07-01 00:00:00.001' AND GETDATE()
--	AND ((CONVERT(int,GETDATE()-1) - CONVERT(int,o.OPP_GENERATED_TIME)) / 90) < 1 -- Rolling 90 days >> Changed 8.2.2023 to starting July 2023
--	AND ((CONVERT(int,GETDATE()-1) - CONVERT(int,o.DATE_INSERTED)) / 90) < 1 -- Rolling 90 days >> Changed 8.2.2023 to starting July 2023
	AND o.OPP_STATUS LIKE 'Resolved%'
	AND o.OPP_RESOLUTION <> 'Accurate but unactionable'
	AND o.[OWNER] NOT LIKE 'Store%'
	AND o.ASSIGNEE NOT IN ('Molly Pollard','Alex Beizerov','analyst profitect','APS Technology','BRETT CAMPBELL','BRIAN ITTNER'
	,'DEREK LANNI','GARY MONAGHAN','Alison Harmon','BILL INZEO','Jim Hare','Investigative Analytics','JACK DONOVAL','JAMES SPENCER','JEFF TOLVA'
	,'JOHN DONOVAL','KIMBERLY GANDY','LAUREN NESTOR','MELISSA VAN DE CARR','RAYMOND NOVAK','RAYMOND STUKEL','SCOTT JONKMAN','RACHEL KAMENIR'
	,'RAY NOVAK','SETH HUGHES','STEPHEN LAMALFA','Zebra Analysts','TAL HAREL','SCOTT MCMULLEN','MICHAEL OADDAMS','JAMES MORRIS','MIKE ROSSI','JIM MORRIS JR','STEPHEN BASUMATARY'
	,'ANTHONY NGUYEN','EKATERINA REVENYUK','SEMETRIUS CANNEDY','SARA MARTEL','BRANDON CAMPBELL','DAMARIS VILLA','ANIL KUMAR SAMPATH KUMAR','MALATHI BABU','TEJASWINI B L','Bhuvaneshwari R')
	AND o.ASSIGNEE NOT LIKE '%KEN O''CONNOR%' AND o.ASSIGNEE NOT LIKE '%KENNETH O''CONNOR%' 
	AND o.EMP_NUMBER_OWNER NOT IN ('4116158','IITeam','1448552') AND o.EMP_NUMBER_OWNER NOT LIKE '%duguay%' -- Tim confirmed 9.9.2021 to REMOVE (EMP_NUMBER_OWNER = 4116158) and ADD ('SteeringCommittee')
	AND o.[OWNER] NOT IN ('Molly Pollard','RAY NOVAK','RAYMOND NOVAK','SEMETRIUS CANNEDY','ANTHONY NGUYEN','EKATERINA REVENYUK','SARA MARTEL','BRANDON CAMPBELL','DAMARIS VILLA'
	,'ANIL KUMAR SAMPATH KUMAR','MALATHI BABU','TEJASWINI B L','Alex Beizerov','STEPHEN BASUMATARY','Bhuvaneshwari R')
	AND o.OPP_ID NOT IN ('2565116','2565168') -- Tim confirmed removal 3.6.2023 bc it is inflating Completed values
	AND o.PATTERN_NAME NOT LIKE 'CP - 705%'
GROUP BY 
	o.OPP_ID,o.SUMMARY,o.OPP_STATUS,o.OPP_RESOLUTION,o.OPP_VALUE,o.ASSIGNEE,o.PATTERN_NAME,o.OPPORTUNITY_ENTITY
	,o.EMP_NUMBER_ASSIGNEE,o.[OWNER],o.EMP_NUMBER_OWNER,o.LABELS,o.DATE_INSERTED,o.OPP_GENERATED_TIME
	,o.ETHICSPOINT_CASE_NUMBER,o.LAST_MODIFIED
ORDER BY 
	o.OPP_ID 
	,CASE 
		WHEN o.OPP_STATUS = 'New' THEN 1 
		WHEN o.OPP_STATUS = 'In progress' THEN 2 
		WHEN o.OPP_STATUS LIKE 'Resolved - %' THEN 3 
			ELSE 9 
		END
	,MIN_LAST_MODIFIED
	; 

-- EPIQ Alert Comments >> STAR SCHEMA 
-- Updated to only bring in OPP_ID from the alerts we are using, not trying to bring in all alerts as previous
SELECT DISTINCT
	pcom.OPP_ID
	,CASE
			WHEN o.[OWNER] LIKE '%store manager%' THEN CAST( RIGHT(o.[OWNER], 5) AS int )
			WHEN LEFT(o.OPPORTUNITY_ENTITY, 7) LIKE '% -%' THEN CAST( LEFT(o.OPPORTUNITY_ENTITY, 5) AS int )
		END AS Store_Number
	,pcom.COMMENT
	,pcom.COMMENT_TIMESTAMP
	,pcom.DATE_INSERTED
FROM i2_data.dbo.PROFITECT_OPPORTUNITIES o
LEFT JOIN i2_data.dbo.PROFITECT_OPPORTUNITY_COMMENTS pcom
	ON o.OPP_ID = pcom.OPP_ID
WHERE 
	o.OPP_STATUS NOT IN ('HISTORY','Deleted')
	AND o.SUMMARY NOT LIKE 'Welcome to%'
	AND o.OPP_GENERATED_TIME BETWEEN '2023-07-01 00:00:00.001' AND GETDATE()
	AND o.DATE_INSERTED BETWEEN '2023-07-01 00:00:00.001' AND GETDATE()
--	AND ((CONVERT(int,GETDATE()-1) - CONVERT(int,o.OPP_GENERATED_TIME)) / 90) < 1 -- Rolling 90 days >> Changed 8.2.2023 to starting July 2023
--	AND ((CONVERT(int,GETDATE()-1) - CONVERT(int,o.DATE_INSERTED)) / 90) < 1 -- Rolling 90 days >> Changed 8.2.2023 to starting July 2023
	AND o.OPP_STATUS LIKE 'Resolved%'
	AND o.OPP_RESOLUTION <> 'Accurate but unactionable'
	AND o.[OWNER] NOT LIKE 'Store%'
	AND o.ASSIGNEE NOT IN ('Molly Pollard','Alex Beizerov','analyst profitect','APS Technology','BRETT CAMPBELL','BRIAN ITTNER'
	,'DEREK LANNI','GARY MONAGHAN','Alison Harmon','BILL INZEO','Jim Hare','Investigative Analytics','JACK DONOVAL','JAMES SPENCER','JEFF TOLVA'
	,'JOHN DONOVAL','KIMBERLY GANDY','LAUREN NESTOR','MELISSA VAN DE CARR','RAYMOND NOVAK','RAYMOND STUKEL','SCOTT JONKMAN','RACHEL KAMENIR'
	,'RAY NOVAK','SETH HUGHES','STEPHEN LAMALFA','Zebra Analysts','TAL HAREL','SCOTT MCMULLEN','MICHAEL OADDAMS','JAMES MORRIS','MIKE ROSSI','JIM MORRIS JR','STEPHEN BASUMATARY'
	,'ANTHONY NGUYEN','EKATERINA REVENYUK','SEMETRIUS CANNEDY','SARA MARTEL','BRANDON CAMPBELL','DAMARIS VILLA','ANIL KUMAR SAMPATH KUMAR','MALATHI BABU','TEJASWINI B L','Bhuvaneshwari R')
	AND o.ASSIGNEE NOT LIKE '%KEN O''CONNOR%' AND o.ASSIGNEE NOT LIKE '%KENNETH O''CONNOR%' 
	AND o.EMP_NUMBER_OWNER NOT IN ('4116158','IITeam','1448552') AND o.EMP_NUMBER_OWNER NOT LIKE '%duguay%' -- Tim confirmed 9.9.2021 to REMOVE (EMP_NUMBER_OWNER = 4116158) and ADD ('SteeringCommittee')
	AND o.[OWNER] NOT IN ('Molly Pollard','RAY NOVAK','RAYMOND NOVAK','SEMETRIUS CANNEDY','ANTHONY NGUYEN','EKATERINA REVENYUK','SARA MARTEL','BRANDON CAMPBELL','DAMARIS VILLA'
	,'ANIL KUMAR SAMPATH KUMAR','MALATHI BABU','TEJASWINI B L','Alex Beizerov','STEPHEN BASUMATARY','Bhuvaneshwari R')
	AND o.OPP_ID NOT IN ('2565116','2565168') -- Tim confirmed removal 3.6.2023 bc it is inflating Completed values
	AND o.PATTERN_NAME NOT LIKE 'CP - 705%'
	AND pcom.OPP_ID IS NOT NULL
ORDER BY 
	pcom.OPP_ID
	,pcom.COMMENT_TIMESTAMP
	;

/*
-- Below was previous location query (which was inactive in PBIX) 
-- STORE / LOCATION / APM POC
SELECT
	apm.POC_APM_EMP_NUM AS APM_Emp_Num
	,emp.FIRST_NAME
	,emp.LAST_NAME
	,emp.FIRST_NAME + ' ' + emp.LAST_NAME AS APM_FULL_NAME
	,emp.WORK_EMAIL_ADDRESS
	,s.LOC_NUM AS STORE_NUMBER
	,CONCAT(FORMAT(s.LOC_NUM,'00000'),' - ',s.CITY,' ,',s.ADDRESS_LINE_1,' ,',s.[STATE]) AS Store
	,d.LOC_NUM AS DISTRICT_NUMBER
	,CONCAT(d.[NAME], ' (', d.LOC_NUM, ')' ) AS DISTRICT
	,a.LOC_NUM AS AREA_NUMBER
	,CONCAT(a.[NAME], ' (', a.LOC_NUM, ')' ) AS AREA
	,r.LOC_NUM AS REGION_NUMBER
	,CONCAT(r.[NAME], ' (', r.LOC_NUM, ')' ) AS REGION
FROM i2_Data.dbo.ATLAS_CONTACTS apm
LEFT OUTER JOIN i2_data.dbo.EISB_LP_FEED emp
	ON apm.POC_APM_EMP_NUM = emp.EMP_NUMBER
LEFT OUTER JOIN i2_Data.dbo.LOCATION s
	ON apm.NODE_ADDRESS = s.NODE_ADDRESS
LEFT OUTER JOIN i2_Data.dbo.LOCATION d
	ON s.PARENT_LOCATION_NUMBER = d.LOC_NUM AND s.PARENT_LOCATION_TYPE_CODE = d.LOC_TYPE_CODE
LEFT OUTER JOIN i2_Data.dbo.LOCATION a
	ON d.PARENT_LOCATION_NUMBER = a.LOC_NUM AND d.PARENT_LOCATION_TYPE_CODE = a.LOC_TYPE_CODE
LEFT OUTER JOIN i2_Data.dbo.LOCATION r
	ON a.PARENT_LOCATION_NUMBER = r.LOC_NUM AND a.PARENT_LOCATION_TYPE_CODE = r.LOC_TYPE_CODE
WHERE
	s.LOC_TYPE_CODE = 'S'
	;


-- Below was previous query. Replaced with above bc n.BRANCH_NUMBER was breaking bc of '13065-%'
-- Updated the CASE statement with above
SELECT 
	n.CASE_NUMBER
	,n.[STATUS]
	,n.CASE_TYPE
	,n.PRIMARY_ISSUE
	,n.PRIMARY_ISSUE_SUBCATEGORY_1
	,n.PRIMARY_ISSUE_SUBCATEGORY_2
	,n.ASSIGNEE AS APD
	,apm.POC_APM_EMP_NUM AS APM_Emp_Num
	,emp.FIRST_NAME
	,emp.LAST_NAME
	,emp.FIRST_NAME + ' ' + emp.LAST_NAME AS APM
	,emp.WORK_EMAIL_ADDRESS
	,n.BRANCH_NUMBER
	,LEFT( n.BRANCH_NUMBER,
		CASE
			WHEN CHARINDEX( ' ', n.BRANCH_NUMBER ) = 0
				THEN  
					CASE 
						WHEN CHARINDEX( '-', n.BRANCH_NUMBER ) = 0
							THEN LEN( n.BRANCH_NUMBER )
								ELSE CHARINDEX( '-', n.BRANCH_NUMBER ) -1
							END 
				ELSE CHARINDEX( ' ', n.BRANCH_NUMBER ) -1
		END) AS STORE_NUM
	,n.LOCATION_ADDRESS
	,n.LOCATION_CITY
	,n.LOCATION_STATE_PROVINCE
	,n.REGION
	,n.REGION_NUMBER
	,n.AREA_NAME
	,n.AREA_NUMBER
	,n.OPENED
	,MIN( n.LAST_MODIFIED ) MIN_LAST_MODIFIED
	,n.DATE_TIME_INSERTED
FROM i2_data.dbo.NAVEX_ETHICSPOINT_CASE_DATA n
/* 
LEFT OUTER JOIN i2_Data.dbo.LOCATION STORE_INFO
	ON STORE_INFO.LOC_TYPE_CODE = 'S' 
		AND STORE_INFO.LOC_NUM = LEFT( n.BRANCH_NUMBER,
				CASE
					WHEN CHARINDEX( ' ', n.BRANCH_NUMBER ) = 0
						THEN  
							CASE 
								WHEN CHARINDEX( '-', n.BRANCH_NUMBER ) = 0
									THEN LEN( n.BRANCH_NUMBER )
										ELSE CHARINDEX( '-', n.BRANCH_NUMBER ) -1
									END 
						ELSE CHARINDEX( ' ', n.BRANCH_NUMBER ) -1
				END)
*/
LEFT OUTER JOIN i2_Data.dbo.ATLAS_CONTACTS apm
	ON CAST(RIGHT(apm.NODE_ADDRESS, 5) AS int) 
		= LEFT( n.BRANCH_NUMBER,
			CASE
				WHEN CHARINDEX( ' ', n.BRANCH_NUMBER ) = 0
					THEN  
						CASE 
							WHEN CHARINDEX( '-', n.BRANCH_NUMBER ) = 0
								THEN LEN( n.BRANCH_NUMBER )
									ELSE CHARINDEX( '-', n.BRANCH_NUMBER ) -1
								END 
					ELSE CHARINDEX( ' ', n.BRANCH_NUMBER ) -1
			END)
LEFT OUTER JOIN i2_data.dbo.EISB_LP_FEED emp
	ON apm.POC_APM_EMP_NUM = emp.EMP_NUMBER
WHERE
	n.OPENED BETWEEN '2023-07-01 00:00:00.001' AND GETDATE()
--	((CONVERT(int,GETDATE()-1) - CONVERT(int,n.OPENED)) / 90) < 1 -- Rolling 90 days >> Changed 8.2.2023 to starting July 2023
	AND n.BRANCH_NUMBER LIKE '%Store%'
	AND n.BRANCH_NUMBER IS NOT NULL
GROUP BY
	n.CASE_NUMBER,n.[STATUS],n.CASE_TYPE,n.PRIMARY_ISSUE,n.PRIMARY_ISSUE_SUBCATEGORY_1,n.PRIMARY_ISSUE_SUBCATEGORY_2,n.ASSIGNEE,apm.POC_APM_EMP_NUM
	,emp.FIRST_NAME,emp.LAST_NAME,emp.WORK_EMAIL_ADDRESS,n.BRANCH_NUMBER,n.LOCATION_ADDRESS,n.LOCATION_CITY,n.LOCATION_STATE_PROVINCE,n.REGION
	,n.REGION_NUMBER,n.AREA_NAME,n.AREA_NUMBER,n.OPENED,n.DATE_TIME_INSERTED
ORDER BY 
	n.CASE_NUMBER
	,CASE
		WHEN n.[STATUS] LIKE '%Unreviewed' THEN 1
		WHEN n.[STATUS] LIKE '%In Process' THEN 2
		WHEN n.[STATUS] LIKE '%Ready for Review' THEN 3
		WHEN n.[STATUS] LIKE '%Closed' THEN 4
			ELSE 9
		END
	,MIN_LAST_MODIFIED
	;

-- with join of LOCATION + APM Contact + EMP Table
	-- Query version 1 >> initial query had LOCATION table joined
		-- above is current active query with LOCATION table removed bc it is not needed and returned same output 
SELECT 
	n.CASE_NUMBER
	,n.ASSIGNEE AS APD
	,apm.POC_APM_EMP_NUM AS APM_Emp_Num
	,emp.FIRST_NAME
	,emp.LAST_NAME
	,emp.FIRST_NAME + ' ' + emp.LAST_NAME AS APM
	,emp.WORK_EMAIL_ADDRESS
	,n.BRANCH_NUMBER
	,LEFT( n.BRANCH_NUMBER,
		CASE
			WHEN CHARINDEX( ' ', n.BRANCH_NUMBER ) = 0
				THEN  
					CASE 
						WHEN CHARINDEX( '-', n.BRANCH_NUMBER ) = 0
							THEN LEN( n.BRANCH_NUMBER )
								ELSE CHARINDEX( '-', n.BRANCH_NUMBER ) -1
							END 
				ELSE CHARINDEX( ' ', n.BRANCH_NUMBER ) -1
		END) AS STORE_NUM
	,n.LOCATION_ADDRESS
	,n.LOCATION_CITY
	,n.LOCATION_STATE_PROVINCE
	,n.REGION
	,n.REGION_NUMBER
	,n.AREA_NAME
	,n.AREA_NUMBER
	,n.OPENED
	,n.LAST_MODIFIED
	,n.DATE_TIME_INSERTED
FROM i2_data.dbo.NAVEX_ETHICSPOINT_CASE_DATA n
LEFT OUTER JOIN i2_Data.dbo.LOCATION STORE_INFO
	ON STORE_INFO.LOC_TYPE_CODE = 'S' 
		AND STORE_INFO.LOC_NUM = LEFT( n.BRANCH_NUMBER,
				CASE
					WHEN CHARINDEX( ' ', n.BRANCH_NUMBER ) = 0
						THEN  
							CASE 
								WHEN CHARINDEX( '-', n.BRANCH_NUMBER ) = 0
									THEN LEN( n.BRANCH_NUMBER )
										ELSE CHARINDEX( '-', n.BRANCH_NUMBER ) -1
									END 
						ELSE CHARINDEX( ' ', n.BRANCH_NUMBER ) -1
				END)
LEFT OUTER JOIN i2_Data.dbo.ATLAS_CONTACTS apm
	ON CAST(RIGHT(apm.NODE_ADDRESS, 5) AS int) 
		= LEFT( n.BRANCH_NUMBER,
			CASE
				WHEN CHARINDEX( ' ', n.BRANCH_NUMBER ) = 0
					THEN  
						CASE 
							WHEN CHARINDEX( '-', n.BRANCH_NUMBER ) = 0
								THEN LEN( n.BRANCH_NUMBER )
									ELSE CHARINDEX( '-', n.BRANCH_NUMBER ) -1
								END 
					ELSE CHARINDEX( ' ', n.BRANCH_NUMBER ) -1
			END)
LEFT OUTER JOIN i2_data.dbo.EISB_LP_FEED emp
	ON apm.POC_APM_EMP_NUM = emp.EMP_NUMBER
WHERE
	((CONVERT(int,GETDATE()-1) - CONVERT(int,n.OPENED)) / 90) < 1 -- Rolling 90 days 
--	n.OPENED BETWEEN '2023-05-01 00:00:00.001' AND GETDATE() -- Previously starting from May 2023 but now updated to rolling 90 days
	AND n.BRANCH_NUMBER LIKE '%Store%'
ORDER BY 
	n.CASE_NUMBER
	,n.LAST_MODIFIED
	;

-- without join of LOCATION + APM Contact + EMP Table
	-- Below is not being used but drafted to mirror above if only NAVEX table is to be used 
SELECT 
	n.CASE_NUMBER
	,n.ASSIGNEE AS APD
	,n.BRANCH_NUMBER
	,LEFT( n.BRANCH_NUMBER,
		CASE
			WHEN CHARINDEX( ' ', n.BRANCH_NUMBER ) = 0
				THEN  
					CASE 
						WHEN CHARINDEX( '-', n.BRANCH_NUMBER ) = 0
							THEN LEN( n.BRANCH_NUMBER )
								ELSE CHARINDEX( '-', n.BRANCH_NUMBER ) -1
							END 
				ELSE CHARINDEX( ' ', n.BRANCH_NUMBER ) -1
		END) AS STORE_NUM
	,n.LOCATION_ADDRESS
	,n.LOCATION_CITY
	,n.LOCATION_STATE_PROVINCE
	,n.REGION
	,n.REGION_NUMBER
	,n.AREA_NAME
	,n.AREA_NUMBER
	,n.OPENED
	,n.LAST_MODIFIED
	,n.DATE_TIME_INSERTED
FROM i2_data.dbo.NAVEX_ETHICSPOINT_CASE_DATA n
WHERE
	n.OPENED BETWEEN '2023-05-01 00:00:00.001' AND GETDATE()
	AND n.BRANCH_NUMBER LIKE '%Store%'
ORDER BY 
	n.CASE_NUMBER
	,n.LAST_MODIFIED
	;
*/