-- APMs which responsible for EPIQ Alert
	-- RESPONSIBILITY_VALUE = District's the APMs are assigned to
		-- This one is tough bc parsing out the RESPONSIBILITY_VALUE without STRING_SPLIT 
	-- RESPONSIBILITY_VALUE = APMs with no districs will not receive EPIQ alerts
SELECT *
FROM i2_Data.dbo.PROFITECT_USERS_APM
	;

-- APM = POC for store or everything that is labeled a store
SELECT *
	,CAST(RIGHT(NODE_ADDRESS, 5) AS numeric) AS Store_Number
FROM i2_Data.dbo.ATLAS_CONTACTS
	;

-- List of APDs by Comp Code
SELECT *
FROM i2_data.dbo.EISB_LP_FEED
WHERE  
	COMPENSATION_CODE = 27363
	;

-- Below are list of FIELD APMs reporting to APDs
	-- APM COMPENSATION_CODE = 29046
SELECT 
	apm.EMP_NUMBER AS APM_EMP_NUMBER
	,CASE
		WHEN apm.EMP_NUMBER IN ('4438507','4464491') 
			THEN
				UPPER(LEFT(apm.FIRST_NAME, 1)) + LOWER(SUBSTRING(apm.FIRST_NAME, 2, LEN(apm.FIRST_NAME))) 
				+ ' ' + UPPER(LEFT(apm.LAST_NAME, 1)) + LOWER(SUBSTRING(apm.LAST_NAME, 2, LEN(apm.LAST_NAME)))
		WHEN apm.EMP_NUMBER IN ('2402374','1844920','2921746') 
			THEN apm.FIRST_NAME + ' ' + apm.LAST_NAME
		WHEN apm.NICKNAME IS NULL 
			THEN apm.FIRST_NAME + ' ' + apm.LAST_NAME
		WHEN apm.EMP_NUMBER = 2948973 
			THEN 'Jim ' + apm.LAST_NAME
				ELSE apm.NICKNAME + ' ' + apm.LAST_NAME
			END AS APM_FULL_NAME
	,apm.FIRST_NAME
	,apm.NICKNAME
	,apm.LAST_NAME
	,LOWER(apm.WORK_EMAIL_ADDRESS) AS APM_EMAIL
	,apm.JOB_TITLE
	,apm.SUPERVISOR_EMP_NUMBER as APD_EMP_NUMBER
	,CASE
		WHEN apd.NICKNAME IS NULL THEN apd.FIRST_NAME + ' ' + apd.LAST_NAME
		 ELSE apd.NICKNAME + ' ' + apd.LAST_NAME
		END AS APD_FULL_NAME
	,apd.FIRST_NAME as APD_FIRST_NAME
	,apd.NICKNAME as APD_NICKNAME
	,apd.LAST_NAME as APD_LAST_NAME
	,LOWER(apd.WORK_EMAIL_ADDRESS) as APD_EMAIL
	,apd.JOB_TITLE
FROM i2_Data.dbo.EISB_LP_FEED apm
LEFT JOIN i2_Data.dbo.EISB_LP_FEED apd
	ON apm.SUPERVISOR_EMP_NUMBER = apd.EMP_NUMBER
WHERE 
	apm.COMPENSATION_CODE = 29046
	;

-- List of all stores + location data + POC APMs for the stores + Supervising APDs to the APMs
	-- Updated to exclude PARENT_LOCATION_NUMBER = 199 
		-- 199 is code for store "Closed/Dead"
-- Updated bc LOCATION table was flattened to add new location category = PODS (LOC_TYPE_CODE = 'F')
	-- New Location Hierarchy = Operations > Region > Area > Pod > District > Store
SELECT 
	apm.EMP_NUMBER AS APM_EMP_NUMBER
	,CASE
		WHEN apm.EMP_NUMBER IN ('4438507','4464491') 
			THEN
				UPPER(LEFT(apm.FIRST_NAME, 1)) + LOWER(SUBSTRING(apm.FIRST_NAME, 2, LEN(apm.FIRST_NAME))) 
				+ ' ' + UPPER(LEFT(apm.LAST_NAME, 1)) + LOWER(SUBSTRING(apm.LAST_NAME, 2, LEN(apm.LAST_NAME)))
		WHEN apm.EMP_NUMBER IN ('2402374','1844920','2921746') 
			THEN apm.FIRST_NAME + ' ' + apm.LAST_NAME
		WHEN apm.NICKNAME IS NULL 
			THEN apm.FIRST_NAME + ' ' + apm.LAST_NAME
		WHEN apm.EMP_NUMBER = 2948973 
			THEN 'Jim ' + apm.LAST_NAME
				ELSE apm.NICKNAME + ' ' + apm.LAST_NAME
			END AS APM_FULL_NAME
	,apm.JOB_TITLE AS APM_TITLE
	,apm.SUPERVISOR_EMP_NUMBER AS APD_EMP_NUMBER
	,CASE
		WHEN apd.NICKNAME IS NULL THEN apd.FIRST_NAME + ' ' + apd.LAST_NAME
		 ELSE apd.NICKNAME + ' ' + apd.LAST_NAME
		END AS APD_FULL_NAME
	,apd.JOB_TITLE AS APD_TITLE
	,s.LOC_NUM AS STORE_NUMBER
	,CONCAT(FORMAT(s.LOC_NUM,'00000'),' - ',s.CITY,', ',s.ADDRESS_LINE_1,', ',s.[STATE]) AS STORE
	,s.DISTRICT_NUMBER
	,CONCAT(s.DISTRICT_NAME, ' (', s.DISTRICT_NUMBER, ')' ) AS DISTRICT
	,s.POD_NUMBER
	,CONCAT(s.POD_NAME, ' (', s.POD_NUMBER, ')' ) AS POD
	,s.AREA_NUMBER
	,CONCAT(s.AREA_NAME, ' (', s.AREA_NUMBER, ')' ) AS AREA
	,s.REGION_NUMBER
	,CONCAT(s.REGION_NAME, ' (', s.REGION_NUMBER, ')' ) AS REGION
FROM i2_Data.dbo.LOCATION s
LEFT JOIN i2_Data.dbo.ATLAS_CONTACTS atlas
	ON atlas.NODE_ADDRESS = s.NODE_ADDRESS
LEFT JOIN i2_Data.dbo.EISB_LP_FEED apm
	ON atlas.POC_APM_EMP_NUM = apm.EMP_NUMBER
LEFT JOIN i2_Data.dbo.EISB_LP_FEED apd
	ON apm.SUPERVISOR_EMP_NUMBER = apd.EMP_NUMBER
WHERE
	s.LOC_TYPE_CODE = 'S'
	AND s.PARENT_LOCATION_NUMBER <> 199
ORDER BY
	s.LOC_NUM ASC
	;

/*
-- Below was initial list but updated to the newest table to include new location category = PODS (LOC_TYPE_CODE = 'F')
-- List of all stores + location data + POC APMs for the stores + Supervising APDs to the APMs
	-- Updated to exclude PARENT_LOCATION_NUMBER = 199 
		-- 199 is code for store "Closed/Dead"
SELECT 
	apm.EMP_NUMBER AS APM_EMP_NUMBER
	,apm.FIRST_NAME
	,apm.NICKNAME
	,apm.LAST_NAME
	,apm.JOB_TITLE
	,apm.SUPERVISOR_EMP_NUMBER as APD_EMP_NUMBER
	,apd.FIRST_NAME as APD_FIRST_NAME
	,apd.NICKNAME as APD_NICKNAME
	,apd.LAST_NAME as APD_LAST_NAME
	,apd.JOB_TITLE
	,s.LOC_NUM AS STORE_NUMBER
	,CONCAT(FORMAT(s.LOC_NUM,'00000'),' - ',s.CITY,', ',s.ADDRESS_LINE_1,', ',s.[STATE]) AS Store
	,d.DISTRICT_NUMBER
	,CONCAT(d.DISTRICT_NAME, ' (', d.DISTRICT_NUMBER, ')' ) AS DISTRICT
	,a.AREA_NUMBER
	,CONCAT(a.AREA_NAME, ' (', a.AREA_NUMBER, ')' ) AS AREA
	,r.REGION_NUMBER
	,CONCAT(r.REGION_NAME, ' (', r.REGION_NUMBER, ')' ) AS REGION
FROM i2_Data.dbo.LOCATION s
LEFT JOIN i2_Data.dbo.ATLAS_CONTACTS atlas
	ON atlas.NODE_ADDRESS = s.NODE_ADDRESS
LEFT JOIN i2_Data.dbo.EISB_LP_FEED apm
	ON atlas.POC_APM_EMP_NUM = apm.EMP_NUMBER
LEFT JOIN i2_Data.dbo.EISB_LP_FEED apd
	ON apm.SUPERVISOR_EMP_NUMBER = apd.EMP_NUMBER
LEFT JOIN i2_Data.dbo.LOCATION d
	ON s.PARENT_LOCATION_NUMBER = d.LOC_NUM AND s.PARENT_LOCATION_TYPE_CODE = d.LOC_TYPE_CODE
LEFT JOIN i2_Data.dbo.LOCATION a
	ON d.PARENT_LOCATION_NUMBER = a.LOC_NUM AND d.PARENT_LOCATION_TYPE_CODE = a.LOC_TYPE_CODE
LEFT JOIN i2_Data.dbo.LOCATION r
	ON a.PARENT_LOCATION_NUMBER = r.LOC_NUM AND a.PARENT_LOCATION_TYPE_CODE = r.LOC_TYPE_CODE
WHERE
	s.LOC_TYPE_CODE = 'S'
	AND s.PARENT_LOCATION_NUMBER <> 199
ORDER BY 
	s.LOC_NUM ASC
	;
*/