-- SOC Western Union Query + COMMENTS
	-- RAD View used bc it has only one row per incident = most recent update to the incident
		-- SOC_ALERTS table is raw data and has mulitple rows for same incident to track updates
	-- Starting from Nov 2022 bc that is when the EPIQ pattern was initially launched
SELECT 
	s.ID AS SOC_CASE_NUMBER
	,s.losses
	,s.recovered
	,s.alert_type
	,s.loss_type
	,s.saSource
	,s.loc_name AS STORE_NUMBER
	,s.region 
	,s.area
	,s.district
	,s.lead_name AS SOC_LEAD_NAME
	,s.spec_name
	,s.POC_APM_EMP_NUM
	,s.comment
	,s.[date]
	,s.LAST_UPDATED_CENTRAL
	,s.LAST_UPDATED_BY
FROM i2_data.dbo.SOC_ALERTS_RAD_VIEW s
WHERE
	s.loss_type LIKE '%Western Union%'
	AND s.[date] BETWEEN '2022-11-01 00:00:00.001' AND GETDATE()
ORDER BY
	s.[date] DESC
	,s.ID
	;

-- STORE / LOCATION / APM POC
SELECT
	apm.POC_APM_EMP_NUM AS APM_Emp_Num
	,emp.FIRST_NAME
	,emp.LAST_NAME
	,emp.FIRST_NAME + ' ' + emp.LAST_NAME AS APM_FULL_NAME
	,emp.WORK_EMAIL_ADDRESS
	,s.LOC_NUM AS STORE_NUMBER
	,CONCAT(FORMAT(s.LOC_NUM,'00000'),' - ',s.CITY,' ,',s.ADDRESS_LINE_1,' ,',s.[STATE]) AS Store
	,d.LOC_NUM AS DISTRICT_NUMBER
	,CONCAT(d.[NAME], ' (', d.LOC_NUM, ')' ) AS DISTRICT
	,a.LOC_NUM AS AREA_NUMBER
	,CONCAT(a.[NAME], ' (', a.LOC_NUM, ')' ) AS AREA
	,r.LOC_NUM AS REGION_NUMBER
	,CONCAT(r.[NAME], ' (', r.LOC_NUM, ')' ) AS REGION
FROM i2_Data.dbo.ATLAS_CONTACTS apm
LEFT OUTER JOIN i2_data.dbo.EISB_LP_FEED emp
	ON apm.POC_APM_EMP_NUM = emp.EMP_NUMBER
LEFT OUTER JOIN i2_Data.dbo.LOCATION s
	ON apm.NODE_ADDRESS = s.NODE_ADDRESS
LEFT OUTER JOIN i2_Data.dbo.LOCATION d
	ON s.PARENT_LOCATION_NUMBER = d.LOC_NUM AND s.PARENT_LOCATION_TYPE_CODE = d.LOC_TYPE_CODE
LEFT OUTER JOIN i2_Data.dbo.LOCATION a
	ON d.PARENT_LOCATION_NUMBER = a.LOC_NUM AND d.PARENT_LOCATION_TYPE_CODE = a.LOC_TYPE_CODE
LEFT OUTER JOIN i2_Data.dbo.LOCATION r
	ON a.PARENT_LOCATION_NUMBER = r.LOC_NUM AND a.PARENT_LOCATION_TYPE_CODE = r.LOC_TYPE_CODE
WHERE
	s.LOC_TYPE_CODE = 'S'
	;

-- Below Query is pretty much the same as PATTERN CENTRIC but looking at alerts for CASH DISCREPANCY patterns
	-- Updated to reflect EMP_NUMBER and removing names of ASSIGNEE/OWNERs from WHERE clause
	-- Starting from Nov 2022 bc that is when the pattern was initially launched
	-- Only Completed Alerts
SELECT 		
	o.OPP_ID
	,o.SUMMARY
	,o.OPP_STATUS
	,o.OPP_RESOLUTION
	,o.OPP_VALUE
	,SUBSTRING(o.PATTERN_NAME, 1, PATINDEX('% %',REPLACE(o.PATTERN_NAME,'CP - ',''))+LEN('CP - ')) PATTERN_CODE
	,o.ASSIGNEE
	,o.EMP_NUMBER_ASSIGNEE
	,CASE
		WHEN o.EMP_NUMBER_OWNER LIKE '%MGR%' THEN CAST(RIGHT(o.EMP_NUMBER_OWNER, 5) AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '2627994' AND o.[OWNER] = 'Rick Gaitan' THEN '1509257'
		WHEN o.EMP_NUMBER_OWNER = '1543428' AND o.[OWNER] = 'Store Manager 05463' THEN CAST('5463' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '1808676' AND o.[OWNER] = 'Store Manager 03197' THEN CAST('3197' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '1991504' AND o.[OWNER] = 'Store Manager 13705' THEN CAST('12705' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '1634916' AND o.[OWNER] = 'Store Manager 15010' THEN CAST('15010' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '2925478' AND o.[OWNER] = 'Store Manager 17217' THEN CAST('17217' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '2923967' AND o.[OWNER] = 'Store Manager 17684' THEN CAST('17684' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = 'SteeringCommittee' THEN CAST('SteeringCommittee' AS nvarchar)
			ELSE o.EMP_NUMBER_OWNER
		END AS EMP_NUMBER_OWNER 
	,CASE
			WHEN o.[OWNER] LIKE '%store manager%' THEN CAST( RIGHT(o.[OWNER], 5) AS int )
			WHEN LEFT(o.OPPORTUNITY_ENTITY, 7) LIKE '% -%' THEN CAST( LEFT(o.OPPORTUNITY_ENTITY, 5) AS int )
		END AS Store_Number
	,o.OPPORTUNITY_ENTITY
	,o.[OWNER]
	,o.LABELS
	,o.OPP_GENERATED_TIME AS CreatedDate -- Added 9.23.2021 > Calendar Table Should be Modeled After This Date
	,MIN(o.LAST_MODIFIED) MIN_LAST_MODIFIED
	,o.DATE_INSERTED
FROM i2_data.dbo.PROFITECT_OPPORTUNITIES o
WHERE 
	o.OPP_STATUS NOT IN ('HISTORY','Deleted')
	AND o.OPP_STATUS LIKE 'Resolved - %'
	AND o.PATTERN_NAME LIKE '%Cash Discrepancy%'
	AND o.DATE_INSERTED BETWEEN '2022-11-01 00:00:00.001' AND GETDATE() -- Tim confirmed 6.30.2021 that FQ2 2020 (Feb 2020) is not needed
	AND o.OPP_GENERATED_TIME BETWEEN '2022-11-01 00:00:00.001' AND GETDATE() -- Was going to replace DATE_INSERTED with this but loss of 4k rows >> RAY confirmed that we can add this filter to get rid of unneccesary historical data 9.28.2021
	AND o.EMP_NUMBER_ASSIGNEE NOT IN ('4118541','4118551','analyst@profitect.com','9999999','1959518','1432914','2634721','1950877','1440795','1445805','jim.hare'
		,'1224862','2982027','2251383','1224862','1222234','2488189','1224384','1223749','2013702','1062954','2223799','4043932','2246468','2860864','IITeam'
		,'2948973','1185165','2948973','4546396','4234682','1863183','1325015','4255465','4256323','1448552','4546413','4546391','4546246','4546399','2589783')
	AND o.EMP_NUMBER_OWNER NOT IN ('4116158','4459658','amanda.duguay@zebra.com','1223749','4546246','4546396') 
	AND o.ASSIGNEE NOT IN ('Zebra Analysts')
GROUP BY 
	o.OPP_ID,o.SUMMARY,o.OPP_STATUS,o.OPP_RESOLUTION,o.OPP_VALUE,o.ASSIGNEE,o.PATTERN_NAME,o.OPPORTUNITY_ENTITY
	,o.EMP_NUMBER_ASSIGNEE,o.[OWNER],o.EMP_NUMBER_OWNER,o.LABELS,o.DATE_INSERTED,o.OPP_GENERATED_TIME
ORDER BY 
	o.OPP_ID 
	,MIN_LAST_MODIFIED
	; 

-- EPIQ Cash Discrepancy Alert Comments >> STAR SCHEMA 
	-- Updated to reflect EMP_NUMBER and removing names of ASSIGNEE/OWNERs from WHERE clause
SELECT DISTINCT
	pcom.OPP_ID
	,CASE
			WHEN o.[OWNER] LIKE '%store manager%' THEN CAST( RIGHT(o.[OWNER], 5) AS int )
			WHEN LEFT(o.OPPORTUNITY_ENTITY, 7) LIKE '% -%' THEN CAST( LEFT(o.OPPORTUNITY_ENTITY, 5) AS int )
		END AS Store_Number
	,pcom.COMMENT
	,pcom.COMMENT_TIMESTAMP
	,pcom.DATE_INSERTED
FROM i2_data.dbo.PROFITECT_OPPORTUNITIES o
LEFT JOIN i2_data.dbo.PROFITECT_OPPORTUNITY_COMMENTS pcom
	ON o.OPP_ID = pcom.OPP_ID
WHERE 
	o.OPP_STATUS NOT IN ('HISTORY','Deleted')
	AND o.OPP_STATUS LIKE 'Resolved - %'
	AND o.PATTERN_NAME LIKE '%Cash Discrepancy%'
	AND o.DATE_INSERTED BETWEEN '2022-11-01 00:00:00.001' AND GETDATE() -- Tim confirmed 6.30.2021 that FQ2 2020 (Feb 2020) is not needed
	AND o.OPP_GENERATED_TIME BETWEEN '2022-11-01 00:00:00.001' AND GETDATE() -- Was going to replace DATE_INSERTED with this but loss of 4k rows >> RAY confirmed that we can add this filter to get rid of unneccesary historical data 9.28.2021
	AND o.EMP_NUMBER_ASSIGNEE NOT IN ('4118541','4118551','analyst@profitect.com','9999999','1959518','1432914','2634721','1950877','1440795','1445805','jim.hare'
		,'1224862','2982027','2251383','1224862','1222234','2488189','1224384','1223749','2013702','1062954','2223799','4043932','2246468','2860864','IITeam'
		,'2948973','1185165','2948973','4546396','4234682','1863183','1325015','4255465','4256323','1448552','4546413','4546391','4546246','4546399','2589783')
	AND o.EMP_NUMBER_OWNER NOT IN ('4116158','4459658','amanda.duguay@zebra.com','1223749','4546246','4546396') 
	AND o.ASSIGNEE NOT IN ('Zebra Analysts')
	AND pcom.OPP_ID IS NOT NULL
ORDER BY 
	pcom.OPP_ID
	,pcom.COMMENT_TIMESTAMP
	;



/*
-- Below was the previous EPIQ Main query and replaced with above 
SELECT 		
	o.OPP_ID
	,o.SUMMARY
	,o.OPP_STATUS
	,o.OPP_RESOLUTION
	,o.OPP_VALUE
	,SUBSTRING(o.PATTERN_NAME, 1, PATINDEX('% %',REPLACE(o.PATTERN_NAME,'CP - ',''))+LEN('CP - ')) PATTERN_CODE
	,o.ASSIGNEE
	,o.EMP_NUMBER_ASSIGNEE
	,CASE
		WHEN o.EMP_NUMBER_OWNER LIKE '%MGR%' THEN CAST(RIGHT(o.EMP_NUMBER_OWNER, 5) AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '2627994' AND o.[OWNER] = 'Rick Gaitan' THEN '1509257'
		WHEN o.EMP_NUMBER_OWNER = '1543428' AND o.[OWNER] = 'Store Manager 05463' THEN CAST('5463' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '1808676' AND o.[OWNER] = 'Store Manager 03197' THEN CAST('3197' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '1991504' AND o.[OWNER] = 'Store Manager 13705' THEN CAST('12705' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '1634916' AND o.[OWNER] = 'Store Manager 15010' THEN CAST('15010' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '2925478' AND o.[OWNER] = 'Store Manager 17217' THEN CAST('17217' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '2923967' AND o.[OWNER] = 'Store Manager 17684' THEN CAST('17684' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = 'SteeringCommittee' THEN CAST('SteeringCommittee' AS nvarchar)
			ELSE o.EMP_NUMBER_OWNER
		END AS EMP_NUMBER_OWNER 
	,CASE
			WHEN o.[OWNER] LIKE '%store manager%' THEN CAST( RIGHT(o.[OWNER], 5) AS int )
			WHEN LEFT(o.OPPORTUNITY_ENTITY, 7) LIKE '% -%' THEN CAST( LEFT(o.OPPORTUNITY_ENTITY, 5) AS int )
		END AS Store_Number
	,o.OPPORTUNITY_ENTITY
	,o.[OWNER]
	,o.LABELS
	,o.OPP_GENERATED_TIME AS CreatedDate -- Added 9.23.2021 > Calendar Table Should be Modeled After This Date
	,MIN(o.LAST_MODIFIED) MIN_LAST_MODIFIED
	,o.DATE_INSERTED
FROM i2_data.dbo.PROFITECT_OPPORTUNITIES o
WHERE 
	o.OPP_STATUS NOT IN ('HISTORY','Deleted')
	AND o.OPP_STATUS LIKE 'Resolved - %'
	AND o.PATTERN_NAME LIKE '%Cash Discrepancy%'
	AND o.DATE_INSERTED BETWEEN '2022-11-01 00:00:00.001' AND GETDATE() -- Tim confirmed 6.30.2021 that FQ2 2020 (Feb 2020) is not needed
	AND o.OPP_GENERATED_TIME BETWEEN '2022-11-01 00:00:00.001' AND GETDATE() -- Was going to replace DATE_INSERTED with this but loss of 4k rows >> RAY confirmed that we can add this filter to get rid of unneccesary historical data 9.28.2021
	AND o.ASSIGNEE NOT IN ('Molly Pollard','Alex Beizerov','analyst profitect','APS Technology','BRETT CAMPBELL','BRIAN ITTNER'
	,'DEREK LANNI','GARY MONAGHAN','Alison Harmon','BILL INZEO','Jim Hare','Investigative Analytics','JACK DONOVAL','JAMES SPENCER','JEFF TOLVA'
	,'JOHN DONOVAL','KIMBERLY GANDY','LAUREN NESTOR','MELISSA VAN DE CARR','RAYMOND NOVAK','RAYMOND STUKEL','SCOTT JONKMAN','RACHEL KAMENIR'
	,'RAY NOVAK','SETH HUGHES','STEPHEN LAMALFA','Zebra Analysts','TAL HAREL','SCOTT MCMULLEN','MICHAEL OADDAMS','JAMES MORRIS','MIKE ROSSI','JIM MORRIS JR','STEPHEN BASUMATARY'
	,'ANTHONY NGUYEN','EKATERINA REVENYUK','SEMETRIUS CANNEDY','SARA MARTEL','BRANDON CAMPBELL','DAMARIS VILLA','ANIL KUMAR SAMPATH KUMAR','MALATHI BABU','TEJASWINI B L','Bhuvaneshwari R')
	AND o.ASSIGNEE NOT LIKE '%KEN O''CONNOR%' AND o.ASSIGNEE NOT LIKE '%KENNETH O''CONNOR%' 
	AND o.EMP_NUMBER_OWNER NOT IN ('4116158','IITeam','1448552') AND o.EMP_NUMBER_OWNER NOT LIKE '%duguay%' -- Tim confirmed 9.9.2021 to REMOVE (EMP_NUMBER_OWNER = 4116158) and ADD ('SteeringCommittee')
	AND o.[OWNER] NOT IN ('Molly Pollard','RAY NOVAK','RAYMOND NOVAK','SEMETRIUS CANNEDY','ANTHONY NGUYEN','EKATERINA REVENYUK','SARA MARTEL','BRANDON CAMPBELL','DAMARIS VILLA'
	,'ANIL KUMAR SAMPATH KUMAR','MALATHI BABU','TEJASWINI B L','Alex Beizerov','STEPHEN BASUMATARY','Bhuvaneshwari R')
GROUP BY 
	o.OPP_ID,o.SUMMARY,o.OPP_STATUS,o.OPP_RESOLUTION,o.OPP_VALUE,o.ASSIGNEE,o.PATTERN_NAME,o.OPPORTUNITY_ENTITY
	,o.EMP_NUMBER_ASSIGNEE,o.[OWNER],o.EMP_NUMBER_OWNER,o.LABELS,o.DATE_INSERTED,o.OPP_GENERATED_TIME
ORDER BY 
	o.OPP_ID 
	,MIN_LAST_MODIFIED; 

-- Below was the previous EPIQ Comments query
-- EPIQ Cash Discrepancy Alert Comments >> STAR SCHEMA 
-- Updated to only bring in OPP_ID from the alerts we are using, not trying to bring in all alerts as previous
SELECT DISTINCT
	pcom.OPP_ID
	,CASE
			WHEN o.[OWNER] LIKE '%store manager%' THEN CAST( RIGHT(o.[OWNER], 5) AS int )
			WHEN LEFT(o.OPPORTUNITY_ENTITY, 7) LIKE '% -%' THEN CAST( LEFT(o.OPPORTUNITY_ENTITY, 5) AS int )
		END AS Store_Number
	,pcom.COMMENT
	,pcom.COMMENT_TIMESTAMP
	,pcom.DATE_INSERTED
FROM i2_data.dbo.PROFITECT_OPPORTUNITIES o
LEFT JOIN i2_data.dbo.PROFITECT_OPPORTUNITY_COMMENTS pcom
	ON o.OPP_ID = pcom.OPP_ID
WHERE 
	o.OPP_STATUS NOT IN ('HISTORY','Deleted')
	AND o.OPP_STATUS LIKE 'Resolved - %'
	AND o.PATTERN_NAME LIKE '%Cash Discrepancy%'
	AND o.DATE_INSERTED BETWEEN '2022-11-01 00:00:00.001' AND GETDATE() -- Tim confirmed 6.30.2021 that FQ2 2020 (Feb 2020) is not needed
	AND o.OPP_GENERATED_TIME BETWEEN '2022-11-01 00:00:00.001' AND GETDATE() -- Was going to replace DATE_INSERTED with this but loss of 4k rows >> RAY confirmed that we can add this filter to get rid of unneccesary historical data 9.28.2021
	AND o.ASSIGNEE NOT IN ('Molly Pollard','Alex Beizerov','analyst profitect','APS Technology','BRETT CAMPBELL','BRIAN ITTNER'
	,'DEREK LANNI','GARY MONAGHAN','Alison Harmon','BILL INZEO','Jim Hare','Investigative Analytics','JACK DONOVAL','JAMES SPENCER','JEFF TOLVA'
	,'JOHN DONOVAL','KIMBERLY GANDY','LAUREN NESTOR','MELISSA VAN DE CARR','RAYMOND NOVAK','RAYMOND STUKEL','SCOTT JONKMAN','RACHEL KAMENIR'
	,'RAY NOVAK','SETH HUGHES','STEPHEN LAMALFA','Zebra Analysts','TAL HAREL','SCOTT MCMULLEN','MICHAEL OADDAMS','JAMES MORRIS','MIKE ROSSI','JIM MORRIS JR','STEPHEN BASUMATARY'
	,'ANTHONY NGUYEN','EKATERINA REVENYUK','SEMETRIUS CANNEDY','SARA MARTEL','BRANDON CAMPBELL','DAMARIS VILLA','ANIL KUMAR SAMPATH KUMAR','MALATHI BABU','TEJASWINI B L','Bhuvaneshwari R')
	AND o.ASSIGNEE NOT LIKE '%KEN O''CONNOR%' AND o.ASSIGNEE NOT LIKE '%KENNETH O''CONNOR%' 
	AND o.EMP_NUMBER_OWNER NOT IN ('4116158','IITeam','1448552') AND o.EMP_NUMBER_OWNER NOT LIKE '%duguay%' -- Tim confirmed 9.9.2021 to REMOVE (EMP_NUMBER_OWNER = 4116158) and ADD ('SteeringCommittee')
	AND o.[OWNER] NOT IN ('Molly Pollard','RAY NOVAK','RAYMOND NOVAK','SEMETRIUS CANNEDY','ANTHONY NGUYEN','EKATERINA REVENYUK','SARA MARTEL','BRANDON CAMPBELL','DAMARIS VILLA'
	,'ANIL KUMAR SAMPATH KUMAR','MALATHI BABU','TEJASWINI B L','Alex Beizerov','STEPHEN BASUMATARY','Bhuvaneshwari R')
	AND pcom.OPP_ID IS NOT NULL
ORDER BY 
	pcom.OPP_ID
	,pcom.COMMENT_TIMESTAMP
	;

-- Count of SOC Alerts by LOSS TYPE
SELECT 
	test.alert_type
	,COUNT( test.id ) count_type
FROM (
	SELECT 
		ID
		,alert_type
		,loss_type
	FROM i2_Data.dbo.SOC_ALERTS_RAD_VIEW
	WHERE
		loss_type LIKE '%Western Union%' 
	) test
GROUP BY test.alert_type
ORDER BY 2 DESC
	;

*/