-- NAVEX cases + EPIQ alerts with join of APM Contact + EMP Table
	-- Query v2: removed LOCATION table
		-- LOCATION table removed bc it is not needed and returned same output 
	-- Query v3: Added Primary Issue + Subcategories 1 & 2
	-- Query v4: Updated CASE statement to fix n.BRANCH_NUMBER
SELECT 
	n.CASE_NUMBER
	,o.OPP_ID
	,o.ETHICSPOINT_CASE_NUMBER
	,SUBSTRING(o.PATTERN_NAME, 1, PATINDEX('% %',REPLACE(o.PATTERN_NAME,'CP - ',''))+LEN('CP - ')) PATTERN_CODE
	,o.SUMMARY
	,n.[STATUS]
	,n.CASE_TYPE
	,n.PRIMARY_ISSUE
	,n.PRIMARY_ISSUE_SUBCATEGORY_1
	,n.PRIMARY_ISSUE_SUBCATEGORY_2
	,n.ASSIGNEE AS APD
	,apm.POC_APM_EMP_NUM AS APM_Emp_Num
	,emp.FIRST_NAME
	,emp.LAST_NAME
	,emp.FIRST_NAME + ' ' + emp.LAST_NAME AS APM
	,n.DETAILS AS COMMENTS
--	,emp.WORK_EMAIL_ADDRESS
	,n.BRANCH_NUMBER
	,CAST(
		REPLACE(
			REPLACE(
				REPLACE(n.BRANCH_NUMBER
					,'Store','')
				,' ','')
			,'-','')
		AS int) AS STORE_NUM
	,n.LOCATION_ADDRESS
	,n.LOCATION_CITY
	,n.LOCATION_STATE_PROVINCE
	,n.REGION
	,n.REGION_NUMBER
	,n.AREA_NAME
	,n.AREA_NUMBER
	,n.OPENED
	,MIN( n.LAST_MODIFIED ) MIN_LAST_MODIFIED
	,n.DATE_TIME_INSERTED
FROM i2_data.dbo.NAVEX_ETHICSPOINT_CASE_DATA n
LEFT OUTER JOIN i2_data.dbo.PROFITECT_OPPORTUNITIES o
	ON n.CASE_NUMBER = 
			CASE
				WHEN o.ETHICSPOINT_CASE_NUMBER IN ('(none)',' ','1','0') THEN NULL 
				WHEN o.ETHICSPOINT_CASE_NUMBER LIKE '%.%' THEN NULL
				WHEN LEN( o.ETHICSPOINT_CASE_NUMBER ) < 6 THEN NULL
					ELSE o.ETHICSPOINT_CASE_NUMBER
			END
/* 
LEFT OUTER JOIN i2_Data.dbo.LOCATION STORE_INFO
	ON STORE_INFO.LOC_TYPE_CODE = 'S' 
		AND STORE_INFO.LOC_NUM = LEFT( n.BRANCH_NUMBER,
				CASE
					WHEN CHARINDEX( ' ', n.BRANCH_NUMBER ) = 0
						THEN  
							CASE 
								WHEN CHARINDEX( '-', n.BRANCH_NUMBER ) = 0
									THEN LEN( n.BRANCH_NUMBER )
										ELSE CHARINDEX( '-', n.BRANCH_NUMBER ) -1
									END 
						ELSE CHARINDEX( ' ', n.BRANCH_NUMBER ) -1
				END)
*/
LEFT OUTER JOIN i2_Data.dbo.ATLAS_CONTACTS apm
	ON CAST(RIGHT(apm.NODE_ADDRESS, 5) AS int) 
		= CAST(
			REPLACE(
				REPLACE(
					REPLACE(n.BRANCH_NUMBER
						,'Store','')
					,' ','')
				,'-','')
			AS int)
LEFT OUTER JOIN i2_data.dbo.EISB_LP_FEED emp
	ON apm.POC_APM_EMP_NUM = emp.EMP_NUMBER
WHERE
	n.OPENED BETWEEN '2023-09-01 00:00:00.001' AND GETDATE()
--	((CONVERT(int,GETDATE()-1) - CONVERT(int,n.OPENED)) / 90) < 1 -- Rolling 90 days >> Changed 8.2.2023 to starting July 2023
	AND n.BRANCH_NUMBER LIKE '%Store%'
	AND n.BRANCH_NUMBER IS NOT NULL
	AND n.DETAILS IS NOT NULL
	AND n.CASE_NUMBER IN (
		SELECT 
			CASE
				WHEN o.ETHICSPOINT_CASE_NUMBER IN ('(none)',' ','1','0') THEN NULL 
				WHEN o.ETHICSPOINT_CASE_NUMBER LIKE '%.%' THEN NULL
				WHEN LEN( o.ETHICSPOINT_CASE_NUMBER ) < 6 THEN NULL
					ELSE o.ETHICSPOINT_CASE_NUMBER
			END AS ETHICSPOINT_CASE_NUMBER
		FROM i2_data.dbo.PROFITECT_OPPORTUNITIES o
		)

GROUP BY
	n.CASE_NUMBER,n.[STATUS],n.CASE_TYPE,n.PRIMARY_ISSUE,n.PRIMARY_ISSUE_SUBCATEGORY_1,n.PRIMARY_ISSUE_SUBCATEGORY_2,n.ASSIGNEE,apm.POC_APM_EMP_NUM
	,emp.FIRST_NAME,emp.LAST_NAME,n.BRANCH_NUMBER,n.LOCATION_ADDRESS,n.LOCATION_CITY,n.LOCATION_STATE_PROVINCE,n.REGION
	,n.REGION_NUMBER,n.AREA_NAME,n.AREA_NUMBER,n.OPENED,n.DATE_TIME_INSERTED
	,n.DETAILS
	,o.ETHICSPOINT_CASE_NUMBER
	,o.PATTERN_NAME
	,o.OPP_ID
	,o.SUMMARY
--	,emp.WORK_EMAIL_ADDRESS
ORDER BY 
	n.CASE_NUMBER
	,CASE
		WHEN n.[STATUS] LIKE '%Unreviewed' THEN 1
		WHEN n.[STATUS] LIKE '%In Process' THEN 2
		WHEN n.[STATUS] LIKE '%Ready for Review' THEN 3
		WHEN n.[STATUS] LIKE '%Closed' THEN 4
			ELSE 9
		END
	,MIN_LAST_MODIFIED
	;

-- EPIQ Alerts >> Below is P18.APM's version
-- Updated to reflect "lifetime" (July 2023 - Present) / Completed Alerts (WITHOUT useless)
	--  Previously truncated to have only ROLLING 90 DAYS
SELECT 
	o.OPP_ID
	,o.SUMMARY
	,o.OPP_STATUS
	,o.OPP_RESOLUTION
	,o.OPP_VALUE
	,SUBSTRING(o.PATTERN_NAME, 1, PATINDEX('% %',REPLACE(o.PATTERN_NAME,'CP - ',''))+LEN('CP - ')) PATTERN_CODE
	,CASE
		WHEN o.ETHICSPOINT_CASE_NUMBER IN ('(none)',' ','1','0') THEN NULL 
		WHEN o.ETHICSPOINT_CASE_NUMBER LIKE '%.%' THEN NULL
		WHEN LEN( o.ETHICSPOINT_CASE_NUMBER ) < 6 THEN NULL
			ELSE o.ETHICSPOINT_CASE_NUMBER
		END AS ETHICSPOINT_CASE_NUMBER
		
	,o.ASSIGNEE
	,o.EMP_NUMBER_ASSIGNEE
	,CASE
		WHEN o.EMP_NUMBER_OWNER LIKE '%MGR%' THEN CAST(RIGHT(o.EMP_NUMBER_OWNER, 5) AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '2627994' AND o.[OWNER] = 'Rick Gaitan' THEN '1509257'
		WHEN o.EMP_NUMBER_OWNER = '1543428' AND o.[OWNER] = 'Store Manager 05463' THEN CAST('5463' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '1808676' AND o.[OWNER] = 'Store Manager 03197' THEN CAST('3197' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '1991504' AND o.[OWNER] = 'Store Manager 13705' THEN CAST('12705' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '1634916' AND o.[OWNER] = 'Store Manager 15010' THEN CAST('15010' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '2925478' AND o.[OWNER] = 'Store Manager 17217' THEN CAST('17217' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = '2923967' AND o.[OWNER] = 'Store Manager 17684' THEN CAST('17684' AS nvarchar)
		WHEN o.EMP_NUMBER_OWNER = 'SteeringCommittee' THEN CAST('SteeringCommittee' AS nvarchar)
			ELSE o.EMP_NUMBER_OWNER
		END AS EMP_NUMBER_OWNER 
	,CASE
			WHEN o.[OWNER] LIKE '%store manager%' THEN CAST( RIGHT(o.[OWNER], 5) AS int )
			WHEN LEFT(o.OPPORTUNITY_ENTITY, 7) LIKE '% -%' THEN CAST( LEFT(o.OPPORTUNITY_ENTITY, 5) AS int )
		END AS Store_Number
	,o.OPPORTUNITY_ENTITY
	,o.[OWNER]

	,o.OPP_GENERATED_TIME AS CreatedDate -- Added 9.23.2021 > Calendar Table Should be Modeled After This Date
	,MIN(o.LAST_MODIFIED) MIN_LAST_MODIFIED
--	,o.DATE_INSERTED
FROM i2_data.dbo.PROFITECT_OPPORTUNITIES o

WHERE 
	o.OPP_STATUS NOT IN ('HISTORY','Deleted')
	AND o.SUMMARY NOT LIKE 'Welcome to%'
	AND o.OPP_GENERATED_TIME BETWEEN '2023-09-01 00:00:00.001' AND GETDATE()
--	AND o.DATE_INSERTED BETWEEN '2023-09-01 00:00:00.001' AND GETDATE()
--	AND ((CONVERT(int,GETDATE()-1) - CONVERT(int,o.OPP_GENERATED_TIME)) / 90) < 1 -- Rolling 90 days >> Changed 8.2.2023 to starting July 2023
--	AND ((CONVERT(int,GETDATE()-1) - CONVERT(int,o.DATE_INSERTED)) / 90) < 1 -- Rolling 90 days >> Changed 8.2.2023 to starting July 2023
	AND o.OPP_STATUS LIKE 'Resolved%'
--	AND o.OPP_RESOLUTION <> 'Accurate but unactionable'
--	AND o.[OWNER] NOT LIKE 'Store%'
	AND o.EMP_NUMBER_ASSIGNEE NOT IN ('4118541','4118551','analyst@profitect.com','9999999','1959518','1432914','2634721','1950877','1440795','1445805','jim.hare'
		,'1224862','2982027','2251383','1224862','1222234','2488189','1224384','1223749','2013702','1062954','2223799','4043932','2246468','2860864','IITeam'
		,'1185165','4546396','4234682','1863183','1325015','4255465','4256323','1448552','4546413','4546391','4546246','4546399','2589783')
	AND o.EMP_NUMBER_OWNER NOT IN ('4116158','4459658','amanda.duguay@zebra.com','1223749','4546246','4546396','4118541','1325015','1863183') 
	AND o.ASSIGNEE NOT IN ('Zebra Analysts')
	AND o.OPP_ID NOT IN ('2565116','2565168') -- Tim confirmed removal 3.6.2023 bc it is inflating Completed values
	AND o.PATTERN_NAME NOT LIKE 'CP - 705%'

GROUP BY 
	o.OPP_ID,o.SUMMARY,o.OPP_STATUS,o.OPP_RESOLUTION,o.OPP_VALUE,o.ASSIGNEE,o.PATTERN_NAME,o.OPPORTUNITY_ENTITY
	,o.EMP_NUMBER_ASSIGNEE,o.[OWNER],o.EMP_NUMBER_OWNER,o.DATE_INSERTED,o.OPP_GENERATED_TIME
	,o.ETHICSPOINT_CASE_NUMBER,o.LAST_MODIFIED

ORDER BY 
	o.OPP_ID 
	,CASE 
		WHEN o.OPP_STATUS = 'New' THEN 1 
		WHEN o.OPP_STATUS = 'In progress' THEN 2 
		WHEN o.OPP_STATUS LIKE 'Resolved - %' THEN 3 
			ELSE 9 
		END
	,MIN_LAST_MODIFIED
	; 

-- EPIQ Alert Comments >> STAR SCHEMA 
-- Updated to only bring in OPP_ID from the alerts we are using, not trying to bring in all alerts as previous
SELECT DISTINCT
	pcom.OPP_ID
	,CASE
			WHEN o.[OWNER] LIKE '%store manager%' THEN CAST( RIGHT(o.[OWNER], 5) AS int )
			WHEN LEFT(o.OPPORTUNITY_ENTITY, 7) LIKE '% -%' THEN CAST( LEFT(o.OPPORTUNITY_ENTITY, 5) AS int )
		END AS Store_Number
	,pcom.COMMENT
	,pcom.COMMENT_TIMESTAMP
FROM i2_data.dbo.PROFITECT_OPPORTUNITIES o
LEFT JOIN i2_data.dbo.PROFITECT_OPPORTUNITY_COMMENTS pcom
	ON o.OPP_ID = pcom.OPP_ID
WHERE 
	o.OPP_STATUS NOT IN ('HISTORY','Deleted')
	AND o.SUMMARY NOT LIKE 'Welcome to%'
	AND o.OPP_GENERATED_TIME BETWEEN '2023-09-01 00:00:00.001' AND GETDATE()
	AND o.DATE_INSERTED BETWEEN '2023-09-01 00:00:00.001' AND GETDATE()
--	AND ((CONVERT(int,GETDATE()-1) - CONVERT(int,o.OPP_GENERATED_TIME)) / 90) < 1 -- Rolling 90 days >> Changed 8.2.2023 to starting July 2023
--	AND ((CONVERT(int,GETDATE()-1) - CONVERT(int,o.DATE_INSERTED)) / 90) < 1 -- Rolling 90 days >> Changed 8.2.2023 to starting July 2023
	AND o.OPP_STATUS LIKE 'Resolved%'
--	AND o.OPP_RESOLUTION <> 'Accurate but unactionable'
--	AND o.[OWNER] NOT LIKE 'Store%'
	AND o.EMP_NUMBER_ASSIGNEE NOT IN ('4118541','4118551','analyst@profitect.com','9999999','1959518','1432914','2634721','1950877','1440795','1445805','jim.hare'
		,'1224862','2982027','2251383','1224862','1222234','2488189','1224384','1223749','2013702','1062954','2223799','4043932','2246468','2860864','IITeam'
		,'1185165','4546396','4234682','1863183','1325015','4255465','4256323','1448552','4546413','4546391','4546246','4546399','2589783')
	AND o.EMP_NUMBER_OWNER NOT IN ('4116158','4459658','amanda.duguay@zebra.com','1223749','4546246','4546396','4118541','1325015','1863183') 
	AND o.ASSIGNEE NOT IN ('Zebra Analysts')
	AND o.OPP_ID NOT IN ('2565116','2565168') -- Tim confirmed removal 3.6.2023 bc it is inflating Completed values
	AND o.PATTERN_NAME NOT LIKE 'CP - 705%'
	AND pcom.OPP_ID IS NOT NULL
ORDER BY 
	pcom.OPP_ID
	,pcom.COMMENT_TIMESTAMP
	;


-- STORE / LOCATION / APM POC
SELECT
	apm.POC_APM_EMP_NUM AS APM_Emp_Num
	,emp.FIRST_NAME
	,emp.LAST_NAME
	,emp.FIRST_NAME + ' ' + emp.LAST_NAME AS APM_FULL_NAME
	,emp.WORK_EMAIL_ADDRESS
	,s.LOC_NUM AS STORE_NUMBER
	,CONCAT(FORMAT(s.LOC_NUM,'00000'),' - ',s.CITY,' ,',s.ADDRESS_LINE_1,' ,',s.[STATE]) AS Store
	,d.LOC_NUM AS DISTRICT_NUMBER
	,CONCAT(d.[NAME], ' (', d.LOC_NUM, ')' ) AS DISTRICT
	,a.LOC_NUM AS AREA_NUMBER
	,CONCAT(a.[NAME], ' (', a.LOC_NUM, ')' ) AS AREA
	,r.LOC_NUM AS REGION_NUMBER
	,CONCAT(r.[NAME], ' (', r.LOC_NUM, ')' ) AS REGION
FROM i2_Data.dbo.ATLAS_CONTACTS apm
LEFT OUTER JOIN i2_data.dbo.EISB_LP_FEED emp
	ON apm.POC_APM_EMP_NUM = emp.EMP_NUMBER
LEFT OUTER JOIN i2_Data.dbo.LOCATION s
	ON apm.NODE_ADDRESS = s.NODE_ADDRESS
LEFT OUTER JOIN i2_Data.dbo.LOCATION d
	ON s.PARENT_LOCATION_NUMBER = d.LOC_NUM AND s.PARENT_LOCATION_TYPE_CODE = d.LOC_TYPE_CODE
LEFT OUTER JOIN i2_Data.dbo.LOCATION a
	ON d.PARENT_LOCATION_NUMBER = a.LOC_NUM AND d.PARENT_LOCATION_TYPE_CODE = a.LOC_TYPE_CODE
LEFT OUTER JOIN i2_Data.dbo.LOCATION r
	ON a.PARENT_LOCATION_NUMBER = r.LOC_NUM AND a.PARENT_LOCATION_TYPE_CODE = r.LOC_TYPE_CODE
WHERE
	s.LOC_TYPE_CODE = 'S'
	;

-- Pattern Group >> Patterns and their recipient groups from ZPA >> WILL HAVE TO BE MAINTAINED!!!!
SELECT 
	pg.PATTERN_CODE
	,pg.OWNER_GROUP
	,CASE
		WHEN pg.ZPA_STATUS = 1 THEN 'Active'
		ELSE 'Inactive'
	END AS ZPA_STATUS
	,pg.PATTERN_SCHEDULE
	,pg.PATTERN_SCHEDULE_RUN_DAY
	,pg.LAST_UPDATED_DTTM
FROM i2_data.dbo.PROFITECT_PATTERNS_BY_OWNER_GROUP pg
	;

/*
-- Below was query for NAVEX Case Comments. Not used bc added comments to the main NAVEX Case Query
-- NAVEX Case Comments >> STAR SCHEMA   
SELECT 
	n.CASE_NUMBER
	,n.DETAILS AS COMMENTS
	,n.OPENED
	,n.LAST_MODIFIED
FROM i2_data.dbo.NAVEX_ETHICSPOINT_CASE_DATA n
WHERE
	n.OPENED BETWEEN '2023-07-01 00:00:00.001' AND GETDATE()
--	((CONVERT(int,GETDATE()-1) - CONVERT(int,n.OPENED)) / 90) < 1 -- Rolling 90 days >> Changed 8.2.2023 to starting July 2023
	AND n.BRANCH_NUMBER LIKE '%Store%'
	AND n.BRANCH_NUMBER IS NOT NULL
ORDER BY
	3 DESC, 4
	;
*/